### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by delta0800** [rayriffy/thai-lotto-api#47]
Hello, i found one issue with 3 front number. Crawled data similar with 3 back number. The others all good. 👍🏻

**Comment by rayriffy** [comment]
Sorry, I didn’t notice this issue until now. I will looking into it as soon as I got my Macbook Pro back.

**Comment by delta0800** [comment]
Good day, 

Anyway i feel glad to receive your reply. Hope i can learn more from you in the future.
All works like a charm actually.

Thanks

**Comment by rayriffy** [comment]
Yes, there’s a duplicate variable there. I may patch this tonight.

https://github.com/rayriffy/thai-lotto-api/blob/ecd8245005049cbea72ddd6a83072ef0ff29e9e0/src/index.js#L130-L136
