### ISSUE TITLE
[core]: Third prize showing 5 of 10

### ISSUE THREAD

**Issue by delta0800** [rayriffy/thai-lotto-api#49]
I found another issue which Prize 3rd have 10 prizes instead of 5. Thanks

**Comment by rayriffy** [comment]
Sorry, I didn't track this issue for a very long time. I will fix this in this week and also with moving from **Heroku** to **Zeit Now**.

**Comment by rayriffy** [comment]
Fixed in 8c162a80c635cddb895172d095563e1873cbc10d

**Comment by delta0800** [comment]
Hello Rayriffy,

Thanks for the fix. Anyway you done a great work. 

Thanks

Sent from Mail for Windows 10
