### ISSUE TITLE
Get specific dates 

### ISSUE THREAD

**Issue by ting-thaiguy** [rayriffy/thai-lotto-api#51]
ถ้าเราอยากได้หวย ของวันที่ ที่ออกได้ไหมครับ เช่น https://lotto.api.rayriffy.com/lotto/2019-12-16

**Comment by ting-thaiguy** [comment]
ขอบคุณมากครับสำหรับ api !! ยอดมากครับ

**Comment by rayriffy** [comment]
สามารถดึง List ของ ID ทั้งหมดจาก `GET /list` ได้ครับ
