### ISSUE TITLE
axios: has been blocked by CORS policy

### ISSUE THREAD

**Issue by menphurk** [rayriffy/thai-lotto-api#58]
Hello
I get axios get but error Cors 
`Access to XMLHttpRequest at 'https://lotto.api.rayriffy.com/lotto/16062564' from origin 'http://localhost:3000' has been blocked by CORS policy: Request header field authorization is not allowed by Access-Control-Allow-Headers in preflight response.`

My code 
`headers: {
              "Access-Control-Allow-Origin": "*",
              "Access-Control-Allow-Methods": "GET,POST,PUT,DELETE,OPTIONS",
              "Access-Control-Allow-Headers":
                "Content-Type, Access-Control-Allow-Headers, Authorization, X-Requested-With",
              "Content-Type":
                "application/x-www-form-urlencoded; charset=UTF-8",
            },
            credentials: true,`

How to fix ??

**Comment by rayriffy** [comment]
`Authorization` header is not allowed into the API, try removing that. There's no need to add those extra headers into axis as well, axis already handled all of the jobs. Just call it normally 

```js
import axios from 'axios'
const { data } = await axios.get('https://lotto.api.rayriffy.com/lotto/16062564')
```
